### ISSUE TITLE
Pin#11 and Pin#13 of orangepi_zero_plus2_H3 don't work. 

### ISSUE THREAD

**Issue by nopnop2002** [Jeremie-C/OrangePi.GPIO#3]
Thank you for useful tool.

Pin#11 and Pin#13 of orangepi_zero_plus2_H3 don't work.
This address doesn't continue.

	import OPi.GPIO as GPIO
	from time import sleep          # this lets us have a time delay
	pin = 11

	GPIO.setboard(GPIO.ZEROPLUS2H3) # Orange Pi ZERO Plus H3 board
	GPIO.setmode(GPIO.BOARD)        # set up BOARD BCM numbering
	GPIO.setup(pin, GPIO.OUT)       # set BCM7 (pin 26) as an output (LED)

	try:
	    print ("Press CTRL+C to exit")
	    while True:
	        GPIO.output(pin, 1)     # set port/pin value to 1/HIGH/True
	        sleep(0.1)
	        GPIO.output(pin, 0)     # set port/pin value to 0/LOW/False
	        sleep(0.1)

	        GPIO.output(pin, 1)     # set port/pin value to 1/HIGH/True
	        sleep(0.1)
	        GPIO.output(pin, 0)     # set port/pin value to 0/LOW/False
	        sleep(0.1)

	        sleep(0.5)

	except KeyboardInterrupt:
	    GPIO.output(pin, 0)         # set port/pin value to 0/LOW/False
	    GPIO.cleanup()              # Clean GPIO
	    print ("Bye.")

**Comment by Jeremie-C** [comment]
Hello.
It's not an Issue.
On Armbian, PL00 (Pin#11) an PL01 (Pin#13) is used for [s_rsb0].
```
cd /boot
bin2fex script.bin > custom.fex
nano custom.fex
```

Near line 816 you can see 
```
[s_rsb0]
s_rsb_used = 1
s_rsb_sck = port:PL00<2><1><2><default>
s_rsb_sda = port:PL01<2><1><2><default>
```
To use Pin#11 and #13 as I/O, ou have to set 
`s_rsb_used = 0`
